language:
- c
addons:
  apt_packages:
os:
- linux
- osx
compiler:
- gcc
script:
- ./build-x86-64.sh
before_deploy:
- mkdir -p $TRAVIS_BUILD_DIR/tls-scan/man/man1
- cp $TRAVIS_BUILD_DIR/ts-build-root/bin/tls-scan $TRAVIS_BUILD_DIR/tls-scan/tls-scan
- cp $TRAVIS_BUILD_DIR/ts-build-root/man/man1/tls-scan.1.gz $TRAVIS_BUILD_DIR/tls-scan/man/man1/tls-scan.1.gz
- cp $TRAVIS_BUILD_DIR/ts-build-root/etc/tls-scan/ca-bundle.crt $TRAVIS_BUILD_DIR/tls-scan/ca-bundle.crt
- tar -zcvf tls-scan-${TRAVIS_OS_NAME}.tar.gz ./tls-scan/
deploy:
  provider: releases
  api_key:
    secure: WvFteHvF84vke+cPXjtwCxLCgiVdOom9gG+KRkhJ2dpwX2Vovbbfo05eOj9CuqLdkK2e94YWz+rrhdgi83rLiLG0HqmrDfo0pCw5x708nWfOtANtN2Kg4BK7qEFBcK45x6RHJ2eW8WpEEgYc2IAMvwz6D0A9Z3Jt8sqFCeB9zmI9WTDDLxD1HZ2fLRzhP7iZmqcdGmZm2Uar/DCGa+HWGCmPdlJ5c2jrylIYTKrJ+G0N9Zpt46D9KpTV+Cpm52czg4lwk13aY2XW/TJoZLYl/qC4OrPLZ51vG/QIs7xk8y7/S2I3c9psmyuKI5dVZm2ac8j/hNBJ1gD+H/h/P32Aq7aV3Nmdca1oNCH1cGM4FbScJONUi/NIKZwI/TuSZEeHCXz4I8NjCttShjNvCKEEgUiJIh8KeTJuOW3XzYvw9UomusXwN466hEr0ugCAv03zOQVUCRR03i4VpmtNRkeCNLyS+ej7Hf8oHMY9EIjog3wCEShF+zuONL7a9yuvBry1PJD88+FyFiuTXlTi+kZFqNrpzORmG6AwU8Sv7myxHWE/FO9l+QNFFGc9rSTPIn4kdVxgNuzrG4xqxCKvaVhXLi72jKZVrfU4ZeQJ30MDeTnuj5Dh+LzWnTkJQkZl4Mj0NQyH4GbQsff7UxvZLnG1O87B3vdAj3rLUo009dfXtgQ=
  file: "tls-scan-$TRAVIS_OS_NAME.tar.gz"
  skip_cleanup: true
  on:
    repo: prbinu/tls-scan
    tags: true
